### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by eMKa091** [eMKa091/Jukebox_LIVE#11]
Pls, for the time being discard the categories idea. I shall provide a .csv file containing an alphabetical song order (based on the author). This is all based of our current feedback...the outcome of the aforementioned feedback is that PEOPLE ARE STUPID! :D

**Comment by eMKa091** [comment]
Zde je CSV které bych tam potřeboval prosím...a bez vedlejšího menu...prozatím...

[Tabulka bez názvu - List 1.csv](https://github.com/user-attachments/files/16879232/Tabulka.bez.nazvu.-.List.1.csv)

**Comment by eMKa091** [comment]
Opraveno, již abecedně seřazeno

[Tabulka bez názvu - List 1(2).csv](https://github.com/user-attachments/files/16879991/Tabulka.bez.nazvu.-.List.1.2.csv)

**Comment by az-fkaw** [comment]
Implemented
