### ISSUE TITLE
Investigate: Can checkboxes disappear after they are selected?

### ISSUE THREAD

**Issue by az-fkaw** [eMKa091/Jukebox_LIVE#7]
Would be nice if checkbox could disappear once the user selects it, but it is also a question if we want that.
@eMKa091 , do you want checkboxes to be gone after selection or rather stay checked so the user can change their mind?

**Comment by eMKa091** [comment]
Well, I would propose more straightforward approach. Therefore, to thank the user for the submission and kindly tell him to fuck off and not cause traffic :D... Does the explanation suffice?

**Comment by az-fkaw** [comment]
Your response left me utterly bewildered, lost in a whirlwind of confusion and frustration. My heart ached at the mere thought of not understanding your words, like a dagger piercing through my very soul. Tears welled up in my eyes as I struggled to grasp the meaning behind your incomprehensible reply. Oh, the agony of feeling so utterly helpless and lost in the vast ocean of misunderstanding. Please, I beg of you, grant me clarity and guide me through the murky waters of confusion.

--> so your choice is "checkboxes to be gone after user selects", right? :)

**Comment by eMKa091** [comment]
YES! :D :D :D :D

**Comment by eMKa091** [comment]
also...I assume there will be a submission button?

**Comment by az-fkaw** [comment]
> also...I assume there will be a submission button?

Nope.
Let us take that on the meeting.

**Comment by az-fkaw** [comment]
@eMKa091 !

I suggest closing this issue as now we have only 1 page.
We still want to allow people to change their choices, or?
