### ISSUE TITLE
Use carrot model to motivate people to vote

### ISSUE THREAD

**Issue by az-fkaw** [eMKa091/Jukebox_LIVE#8]
Since we are generating random number for each user and ask them for their nickname, we can do ruffle ("tombola")
and whoever wins can have one song played just for them, no matter the voting results.

This presents a good carrot for people to participate in voting.

If agreed with promoters, the prize might be whatever (glass of wine, beer, food, ....).

Scenario:
Let's say we limit the voting time - 7 - 10 PM.
At 10:30, we can code a random pick of a nickname (= person) and present them the price.
Nice, isn't it?

@eMKa091 - your thoughts?
Maybe something to bring up with the gang.

**Comment by eMKa091** [comment]
Great idea...will submit propositions later!

**Comment by eMKa091** [comment]
We thought about it and let's have a meeting regarding the above...I'd like to do some brainstorming before introducing the 'carrot model'...

**Comment by az-fkaw** [comment]
@eMKa091 .

How about this?

**Comment by az-fkaw** [comment]
Closing - no reply.
However, will code v2 so it supports such scenario.
